name: Sync Fork with Upstream

on:
  repository_dispatch:
    types: [sync-fork]

jobs:
  sync:
    if: github.repository == 'ahmdfauzanf/responsive-navbar'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/ahmadfauzanf/responsive-navbar.git
          git fetch upstream main

      - name: Merge Changes from Upstream
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Push Changes to Fork
        run: |
          git push origin main
