name: Sync Fork with Upstream

on:
  workflow_dispatch:

jobs:
  sync:
    if: github.repository == 'ahmdfauzanf/responsive-navbar'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3                                     
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/ahmadfauzanf/responsive-navbar.git
          git fetch upstream main
          git config --global pull.rebase true

      - name: Merge Changes from Upstream
        run: |
          git checkout main
          git merge upstream/main --no-edit || git rebase upstream/main                                                   

      - name: Push Changes to Fork
        run: |
          git push https://x-access-token:${{ secrets.PAT_GITHUB}}@github.com/ahmdfauzanf/responsive-navbar.git main --force

      - name: Send Dispatch Event
        env:
          TOKEN: ${{ secrets.PAT_GITHUB}}
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $TOKEN" \
           https://api.github.com/repos/ahmdfauzanf/responsive-navbar/actions/workflows/production.yml/dispatches \
           -d '{"ref":"main"}'  