name: Sync Fork to Upstream and Create PR

on:
  push:
    branches:
      - main

jobs:
  sync_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_GITHUB }}

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/ahmadfauzanf/responsive-navbar.git
          git fetch upstream main

      - name: Create sync branch
        run: |
          git checkout -b sync-to-upstream
          git push --force https://x-access-token:${{ secrets.PAT_GITHUB }}@github.com/ahmdfauzanf/responsive-navbar.git sync-to-upstream

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.PAT_GITHUB }}" | gh auth login --with-token

      - name: Create Pull Request to upstream
        run: |
          gh pr create \
            --base main \
            --head ahmdfauzanf:sync-to-upstream \
            --title "Sync: Update from fork" \
            --body "Auto-generated PR to sync changes from fork to upstream" \
            --repo ahmadfauzanf/responsive-navbar
