name: Vercel Production Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Lint:
    if: github.repository == 'ahmdfauzanf/responsive-navbar'
    uses: ./.github/workflows/lint.yml

  Deploy-Production:
    runs-on: ubuntu-latest
    needs: Lint
    environment: Production
    if: >-
      github.repository == 'ahmdfauzanf/responsive-navbar' &&
      github.actor != 'andrijunaedi' && github.actor != 'aldycavalera'
    steps:
      - name: Trigger CURL Hook
        run: curl -X POST -d {} ${{ vars.VERCEL_DEPLOY_HOOK }}
