name: Create PR to sawala-tech

on:
  push:
    branches:
      - main

jobs:
  check_update:
    if: github.repository == 'ahmdfauzanf/responsive-navbar'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Committer Info
        id: commit_info
        run: |
          echo "COMMITTER_NAME=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "COMMITTER_EMAIL=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

      - name: Setup Git
        run: |
          git config --global user.name "$COMMITTER_NAME"
          git config --global user.email "$COMMITTER_EMAIL"

      - name: Add sawala-tech as remote
        run: |
          git remote add sawala-tech https://github.com/ahmadfauzanf/responsive-navbar.git
          git fetch sawala-tech

      - name: Push changes to sawala-tech
        run: |
          git checkout -b sync-from-projects
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ahmadfauzanf/responsive-navbar.git sync-from-projects

      - name: Create Pull Request to sawala-tech/tifa-next-api
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync from sawala-projects/tifa-next-api"
          title: "Sync: Update from sawala-projects/tifa-next-api"
          body: "Auto-generated PR to sync changes from sawala-projects/tifa-next-api"
          base: main
          branch: sync-from-projects
          delete-branch: true
