name: Trigger Fork Sync

on:
  push:
    branches:
      - main

jobs:
  trigger-sync:
    if: github.repository == 'ahmadfauzanf/responsive-navbar'
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout sawala-tech/tifa-next-api
        uses: actions/checkout@v3

      - name: Send Dispatch Event
        env:
          TOKEN: ${{ secrets.PAT_GITHUB}}
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer $TOKEN" \
               https://api.github.com/repos/ahmdfauzanf/responsive-navbar/actions/workflows/prj-sync-fork.yml/dispatches \
               -d '{"ref":"main"}'